name: Deploy Theme
on:
  push:	
    branches:	
      - test-action
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Deploy Ghost Theme
        uses: mrkwse/action-deploy-theme@mrkwse/actions-missing-key
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          theme-name: 'casper-deploy-test'